# Base image extends debian:buster-slim
FROM rust:slim-bookworm as build

# Init Repo for building dependencies and caching them for later use
WORKDIR /tmp
RUN cargo init --vcs none main
COPY Cargo.toml ./main
WORKDIR /tmp/main
RUN cargo build --release